services:
  - type: web
    name: spotify-recommender
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10